### ISSUE TITLE
CentOS 8

### ISSUE THREAD

**Issue by ghost** [hnakamur/luajit-rpm#14]
Hello,

I tried to build it for CentOS 8 but I still fail …

My git patch
[centos8.diff.txt](https://github.com/hnakamur/luajit-rpm/files/3653276/centos8.diff.txt)

Regards

Florent

**Comment by hnakamur** [comment]
Sorry I didn't notice this issue.
I'm afraid I can't help you since I don't use CentOS 8.
Maybe you can see the spec file in a nginx.org official SRPM at
http://nginx.org/packages/mainline/centos/8/SRPMS/

**Comment by hnakamur** [comment]
Sorry my mistake, this is luajit repository not nginx.

**Comment by hnakamur** [comment]
I don't know but maybe you can look spec file in OpenResty or CentOS 8 luajit package.
